# Generated by Django 6.0.2 on 2026-02-09 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
